file_format: "1"
id: 1984x
name: 1984x
type: shield
url: https://github.com/dilshod/36-choc-key-ortholinear-split
requires: [seeed_xiao]
exposes: [i2c_oled]
features:
  - keys
  - pointer
siblings:
  - 1984x_left
  - 1984x_right
