description: Trackball LED Control Behavior

compatible: "zmk,behavior-trackball-led"

properties:
  red:
    type: int
    default: 0
    description: Red component of LED color (0-255)
  green:
    type: int
    default: 0
    description: Green component of LED color (0-255)
  blue:
    type: int
    default: 0
    description: Blue component of LED color (0-255)
  white:
    type: int
    default: 0
    description: White component of LED color (0-255)