manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/t0bybr
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: integrate-pim447
      import: app/west.yml
  self:
    path: config
