manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
        #url-base: https://github.com/t0bybr
    - name: pim447
      url-base: https://github.com/cdc-mkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: mouse-pim447
      remote: pim447
      revision: mouse-pim447
  self:
    path: config
