manifest:
  remotes:
    - name: zmkfirmware
      #url-base: https://github.com/zmkfirmware
      #url-base: https://github.com/t0bybr
      url-base: https://github.com/cdc-mkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
